# Generated by Django 5.0 on 2023-12-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystemvendor', '0002_alter_vendor_contact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('items', models.TextField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managesystemvendor.vendor')),
            ],
        ),
    ]
