# Generated by Django 5.0 on 2023-12-06 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystemvendor', '0005_purchaseorder_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 10, 34, 18, 592195, tzinfo=datetime.timezone.utc)),
        ),
    ]
